### ISSUE TITLE
JSP Error

### ISSUE THREAD

**Issue by dubfib** [tnfAngel/jspaste-api#11]
2022-02-27T16:19:07.760845+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Error: [JSP Error ERROR_ON_REQUEST] => undefined

2022-02-27T16:19:07.760875+00:00 app[worker.1]:     at Function.Error (/app/node_modules/jspaste/src/misc/handler.js:12:15)

2022-02-27T16:19:07.760875+00:00 app[worker.1]:     at a.post.catch.e (/app/node_modules/jspaste/src/methods.js:72:40)

2022-02-27T16:19:07.760875+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:86:5)

2022-02-27T16:19:07.760896+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

2022-02-27T16:19:07.760933+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tnfAngel** [comment]
Hello, can you specify the version of the library? Thanks

**Comment by dubfib** [comment]
Sorry about that, its fixed.
